swipe:
  2:
    left:
      sendkey: "LEFTALT+RIGHT"
    right:
      sendkey: "LEFTALT+LEFT"
  3:
    left:
      sendkey: "LEFTCTRL+PAGEUP" # History back
    right:
      sendkey: "LEFTCTRL+PAGEDOWN" # History forward
    up:
      sendkey: "LEFTCTRL+T" # Open a new tab
    down:
      sendkey: "LEFTCTRL+W" # Close a tab

hold:
  3:
    sendkey: "F5" # Refresh page
  4:
    sendkey: "LEFTMETA+W" # Close application

threshold:
  swipe: 0.5

interval:
  swipe: 1.5
